// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9bnX5JBSiBx58IcXzU27IRjjwP2T1AKc',
    appId: '1:547541419448:web:68033fd66a9cf8eacffb4d',
    messagingSenderId: '547541419448',
    projectId: 'smartcacao-c1cd7',
    authDomain: 'smartcacao-c1cd7.firebaseapp.com',
    storageBucket: 'smartcacao-c1cd7.firebasestorage.app',
    measurementId: 'G-TY1VVV6KSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYkCP8pGlE5tjHbWacMKL3evxZlGo7Ek',
    appId: '1:547541419448:android:775d6a6894e0e41acffb4d',
    messagingSenderId: '547541419448',
    projectId: 'smartcacao-c1cd7',
    storageBucket: 'smartcacao-c1cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dmiQiWm9qbQERrnsQO0nupo4Q0a5SW0',
    appId: '1:547541419448:ios:07403ce00b782df4cffb4d',
    messagingSenderId: '547541419448',
    projectId: 'smartcacao-c1cd7',
    storageBucket: 'smartcacao-c1cd7.firebasestorage.app',
    iosBundleId: 'com.example.smartcacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dmiQiWm9qbQERrnsQO0nupo4Q0a5SW0',
    appId: '1:547541419448:ios:07403ce00b782df4cffb4d',
    messagingSenderId: '547541419448',
    projectId: 'smartcacao-c1cd7',
    storageBucket: 'smartcacao-c1cd7.firebasestorage.app',
    iosBundleId: 'com.example.smartcacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9bnX5JBSiBx58IcXzU27IRjjwP2T1AKc',
    appId: '1:547541419448:web:cbd087e40e8607f7cffb4d',
    messagingSenderId: '547541419448',
    projectId: 'smartcacao-c1cd7',
    authDomain: 'smartcacao-c1cd7.firebaseapp.com',
    storageBucket: 'smartcacao-c1cd7.firebasestorage.app',
    measurementId: 'G-XLTMWZGYK6',
  );
}
