// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANyZ486d1dBeN3bPES56oylDoXAYtCxxc',
    appId: '1:791253354174:web:e34273acd233985f7200ef',
    messagingSenderId: '791253354174',
    projectId: 'smartcacao-8e955',
    authDomain: 'smartcacao-8e955.firebaseapp.com',
    storageBucket: 'smartcacao-8e955.firebasestorage.app',
    measurementId: 'G-8KC19YXRWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYye9jio_unX7n8cciHD7Fw53nZFUSZH4',
    appId: '1:791253354174:android:c195b043e959435e7200ef',
    messagingSenderId: '791253354174',
    projectId: 'smartcacao-8e955',
    storageBucket: 'smartcacao-8e955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbuwml1tJPE8WNs1Sv112oPU9vDrgUTI',
    appId: '1:791253354174:ios:8f8a2124e0f145287200ef',
    messagingSenderId: '791253354174',
    projectId: 'smartcacao-8e955',
    storageBucket: 'smartcacao-8e955.firebasestorage.app',
    iosBundleId: 'com.example.smartcacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbuwml1tJPE8WNs1Sv112oPU9vDrgUTI',
    appId: '1:791253354174:ios:8f8a2124e0f145287200ef',
    messagingSenderId: '791253354174',
    projectId: 'smartcacao-8e955',
    storageBucket: 'smartcacao-8e955.firebasestorage.app',
    iosBundleId: 'com.example.smartcacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANyZ486d1dBeN3bPES56oylDoXAYtCxxc',
    appId: '1:791253354174:web:f13a2e1410a1e8387200ef',
    messagingSenderId: '791253354174',
    projectId: 'smartcacao-8e955',
    authDomain: 'smartcacao-8e955.firebaseapp.com',
    storageBucket: 'smartcacao-8e955.firebasestorage.app',
    measurementId: 'G-6JCV59V0HJ',
  );
}
